
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: picgram_development


test:
  <<: *default
  database: picgram_test


production:
  <<: *default
  database: picgram_production
  username: picgram
  password: <%= ENV['PICGRAM_DATABASE_PASSWORD'] %>
